### PR TITLE
Zarafa

### PR DESCRIPTION
**Pull request by flok99**
Applies to pops, imaps, caldavs and client-server.

### CODE REVIEW

**Comment by RaymiiOrg** [comment]
Can you maybe add a config file location where this should go?

Like so:

    # /etc/example/conf.conf

**Comment by flok99** [comment]
I'm not entirely fluent in githubs but if I understood it correctly then I
added the requested details.

On Tue, Aug 4, 2015 at 10:07 AM, Raymii <notifications@github.com> wrote:

> Can you maybe add a config file location where this should go?
>
> Like so:
>
> # /etc/example/conf.conf
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RaymiiOrg/cipherli.st/pull/45#issuecomment-127554112>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by RaymiiOrg** [comment]
Super, thanks!

**Comment by flok99** [comment]
It has not been uploaded to the website?

On Thu, Aug 6, 2015 at 5:25 AM, Raymii <notifications@github.com> wrote:

> Super, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RaymiiOrg/cipherli.st/pull/45#issuecomment-128224795>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Pull request merged**
